version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: real_estate
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  bot:
    build: .
    command: python main.py
    environment:
      TELEGRAM_API_TOKEN: ${TELEGRAM_API_TOKEN}
      FLASK_SECRET_KEY: supersecretkey
      DATABASE_URL: postgresql+asyncpg://user:pass@db:5432/real_estate
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A celery_worker.celery_app worker --loglevel=info
    depends_on:
      - redis
      - db

volumes:
  pgdata: